version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maintenance_pro_app
    volumes:
      - .:/app
      - /app/vendor
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: maintenance_pro_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge