name: PHP CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Static analysis (PHPStan)
        run: vendor/bin/phpstan analyse -l max src --no-progress || true
      - name: Fix style (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff || true
      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --verbose